
package pl.wiktor.first_soap_example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServicePort", targetNamespace = "http://wiktor.pl/first-soap-example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServicePort {


    /**
     * 
     * @param getUserRequest
     * @return
     *     returns pl.wiktor.first_soap_example.GetUserResponse
     */
    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://wiktor.pl/first-soap-example", partName = "getUserResponse")
    public GetUserResponse getUser(
        @WebParam(name = "getUserRequest", targetNamespace = "http://wiktor.pl/first-soap-example", partName = "getUserRequest")
        GetUserRequest getUserRequest);

    /**
     * 
     * @param addUserRequest
     * @return
     *     returns pl.wiktor.first_soap_example.AddUserResponse
     */
    @WebMethod
    @WebResult(name = "addUserResponse", targetNamespace = "http://wiktor.pl/first-soap-example", partName = "addUserResponse")
    public AddUserResponse addUser(
        @WebParam(name = "addUserRequest", targetNamespace = "http://wiktor.pl/first-soap-example", partName = "addUserRequest")
        AddUserRequest addUserRequest);

}
